{
 "title": "HVAC System",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "\r\nSELECT\r\n    MAX(CASE WHEN mv.browse_name = 'Sim_SupplyTemp_GT71_01' THEN sd.field_value END) AS Sim_SupplyTemp_GT71_01,\r\n    MAX(CASE WHEN mv.browse_name = 'Sim_ExhaustTemp_GT72_01' THEN sd.field_value END) AS Sim_ExhaustTemp_GT72_01,\r\n    MAX(CASE WHEN mv.browse_name = 'Sim_ReturnTemp_GT81_01' THEN sd.field_value END) AS Sim_ReturnTemp_GT81_01,\r\n    MAX(sd.timestamp) as timestamp\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name IN ('Sim_SupplyTemp_GT71_01', 'Sim_ExhaustTemp_GT72_01','Sim_ReturnTemp_GT81_01');\r\n\r\n"
    }
   ]
  },
  {
   "title": "Energy Valve",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'SV71_01_Pct'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'OutdoorTemp_GT10_01'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Outdor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'OutdoorTemp_GT10_01'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Outdoor Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'OutdoorHumidity_GT10_01'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 100;\r\n"
    }
   ]
  }
 ]
}